#!/usr/bin/perl

use 5.014;

sub usage () {
  say <<HERE

 NAME
   abc2dec - Convert a spreadsheet letter column identifier to
             a decimal value
 SYNOPSIS
   abc2dec COLUMN_IDENTIFIER

 EXAAMPLE

  > abc2dec A
  1

  > abc2dec Z
  26

  > abc2dec AB
  28
HERE
}

my ( $ABC_number, $decimal_number ) = ( undef, 0 );

my %table = (
  A =>  1, B =>  2, C =>  3, D =>  4, E =>  5, F =>  6, G =>  7, H =>  8, I =>  9,
  J => 10, K => 11, L => 12, M => 13, N => 14, O => 15, P => 16, Q => 17, R => 18,
  S => 19, T => 20, U => 21, V => 22, W => 23, X => 24, Y => 25, Z => 26,
);


if ( defined $ARGV[0] ) {
  usage if $ARGV[0] =~ /h[elp]/;

  if ( $ARGV[0] !~ /[\d]/g ) {
    $ABC_number = uc $ARGV[0];
  }
  else {
    usage && exit
  }
}
else {
  usage && exit
}


my @letters = split //, $ABC_number;
my $exponent = scalar @letters - 1;

foreach ( @letters ) {
  my $number = $table{$_};

  if ( $exponent ) {
    $decimal_number = $decimal_number + $number * (26**$exponent)
  }
  else {
    $decimal_number = $decimal_number + $number;
    last
  }

  $exponent--;
}

say $decimal_number;
#SDG
